dist: trusty
sudo: true

language: rust
rust:
    - nightly
cache: cargo

addons:
    apt:
        packages:
            - cmake
            - golang

install:
    - curl -OL https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-linux-x86_64.zip
    - unzip protoc-3.5.0-linux-x86_64.zip -d protoc3
    - sudo mv protoc3/bin/* /usr/local/bin/
    - sudo mv protoc3/include/* /usr/local/include/

script:
    - cargo build --verbose --all
    - cargo test --verbose --all
