[package]
name = "cli"
version = "0.2.0"
authors = ["Cerberus Authors <cerberus@cpssd.net>"]

[dependencies]
clap = "~2.26"
error-chain = "0.11.0"
grpc = "0.2.1"
chrono = "0.4.0"
prettytable-rs = "^0.6"
cerberus-proto = { path = "../proto" }
