[package]
name = "cerberus"
version = "0.0.0"
authors = ["Cerberus Authors <cerberus@cpssd.net>"]

[dependencies]
error-chain = "0.11.0"
log = "0.3.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
