[package]
name = "cerberus"
version = "0.0.0"
authors = ["Cerberus Authors <cerberus@cpssd.net>"]

[dependencies]
chrono = "0.4"
clap = "2.26"
error-chain = "0.11.0"
log = "0.3.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.5", features = ["v4"] }
