[package]
name = "master"
version = "0.1.0"
authors = ["Cerberus Authors <cerberus@cpssd.net>"]

[dependencies]
cerberus-proto = { path = "../proto" }
env_logger = "0.4.3"
error-chain = "0.11.0"
grpc = "0.2.1"
log = "0.3"
util = { path = "../util" }
uuid = { version = "0.5", features = ["v4"] }
