[package]
name = "master"
version = "0.1.0"
authors = ["Cerberus Authors <cerberus@cpssd.net>"]

[dependencies]
env_logger = "0.4.3"
error-chain = "0.11.0"
grpc = "0.2.1"
log = "0.3"
uuid = { version = "0.5", features = ["v4"] }
cerberus-proto = { path = "../proto" }
